version: "3.1"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
     - ./html:/usr/share/nginx/html
#     - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "8080:80"
